### ISSUE TITLE
Memory increases forever

### ISSUE THREAD

**Issue by endolith** [ignamv/ngspyce#11]
If I do hundreds of simulations (experimenting with circuit optimization) the memory usage just increases forever.  

after 0:
```
['Total elapsed time: 3.081 seconds.',
 'Total DRAM available = 8072.601563 MB.',
 'DRAM currently available = 5075.894531 MB.',
 'Total ngspice program size = 2.312500 MB.']
```

after 1000:
```
['Total elapsed time: 75.566 seconds.',
 'Total DRAM available = 8072.601563 MB.',
 'DRAM currently available = 3778.500000 MB.',
 'Total ngspice program size = 1320.335938 MB.']
```

after thousands:
```
['Total elapsed time: 2419.410 seconds.',
 'Total DRAM available = 8072.601563 MB.',
 'DRAM currently available = 425.308594 MB.',
 'Total ngspice program size = 2960.398438 MB.']
```

I'm calling `ngspyce.destroy()` after each simulation, but it's still increasing continually.

![2017-08-25 23_26_37-windows task manager](https://user-images.githubusercontent.com/58611/29738336-558f6f0e-89ee-11e7-87cb-d8be8c6eea0f.png)

I can't find any way to clear the memory except to completely restart python

Manual says 

> The simulation result remains in memory until the libspice library is unloaded (typically:
when the tcl script ends) or when a spice::clean command is performed.

But I don't know what `spice::clean` means.

I can't call `ngspyce.initalize()` to clear it, it gives an exception:

    OSError: exception: access violation writing 0x0000000180610CE0

I tried `remcirc`, `reset`, `save none` but none of them clear memory.  `quit` results in a stack overflow.

`CKTdestroy` supposedly does it, but I don't know how to call that.

```
>>> import sys
>>> sys.modules[__name__].__dict__.clear()
```
does not clear memory but breaks lots of other things

```
from importlib import reload
reload(ngspyce)
```

doesn't clear memory

Went through the trouble of learning how to make a DLL unload() function and that doesn't clear memory either:

```
def unload():
    kernel32 = ctypes.WinDLL('kernel32')
    kernel32.FreeLibrary.argtypes = [ctypes.wintypes.HMODULE]

    handle = spice._handle # obtain the DLL handle
    kernel32.FreeLibrary(handle)

```

**Comment by ignamv** [comment]
ngspice frees memory correctly. Here is some test code:

```
import resource
import ngspyce as ns
from matplotlib import pyplot as plt
%matplotlib inline
memory = []
for ii in range(10000):
    ns.cmd('dc v 0 100 5')
    ns.destroy()
    memory.append(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)

plt.plot(memory)
plt.show()
```
This gives you a flat plot, unlike with `ngspyce.dc`

I'll try to find where I'm leaking memory.

**Comment by ignamv** [comment]
Maybe ngspice is at fault. Merely getting vector information causes linear memory growth:

```
import resource
import ngspyce as ns
from matplotlib import pyplot as plt
import ngspyce.ngspyce
%matplotlib inline
ns.circ('\n'.join('v{n} n{n} 0 dc 1'.format(n=n) for n in range(100)))
memory = []
for ii in range(1000):
    ns.cmd('dc v2 0 100 5')
    ngspyce.ngspyce.spice.ngGet_Vec_Info(b'n4')
    ns.destroy()
    memory.append(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)

plt.plot(memory)
plt.show()
```

The manual does not talk about freeing the memory after use.

**Comment by endolith** [comment]
Is there any way to clear it without stopping the Python interpreter?  Even completely resetting ngspice is fine.

**Comment by eps82** [comment]
Hello, I recently wrote my own wrapper library because I didn't like many of the "extras" people were adding and I came across the same problem (I know it's a bit absurd that there are so many small projects diverting people's efforts, but this was small enough to be worth redoing for myself). Ngspice indeed leaks memory, but this is easy to solve by detaching/reattaching the shared library. I solved it with a reset method that simply reloads the library, flushing the leak.

I intend to also upload my module somewhere soon but in the meantime there's no reason not to share :) The idea is to first send a quit command to do a controlled ngspice exit and then free it.

I find it strange that your FreeLibrary doesn't work because I think it's exactly what _ctypes's FreeLibrary calls. I haven't gone through your proposed steps but maybe it has a different side-effect. I have:

```python
try:
  from _ctypes import dlclose # Linux
except:
  from _ctypes import FreeLibrary as dlclose # Windows

...

  def __detach(self):
    self.command('quit')
    dlclose(self._shared._handle)  # My self._shared is your spice

```` 

I also have an __attach() method in the ngspice class (where I put most of my stuff), the one that initializes my self._shared (I call it in my __init__(), and then reset() does __detach/__attach in one go). 

Hope this helps

**Comment by ignamv** [comment]
Seems related to [this comment](https://sourceforge.net/p/ngspice/discussion/133842/thread/d29f4768/#1218). If I use `ngGet_Vec_Info(b'all')` then memory grows much slower, because the plot hash table doesn't get allocated. 

There's also a list of old commands which slowly grows forever.

I've submitted a patch to ngspice. You can use the code [here](https://github.com/ignamv/ngspice/commit/6ab97c8504aab3e5f93365ca0c0cf68a5fc65562) if you're in a hurry. You have to periodically run command "clearlabels" to deal with the command list leak.

**Comment by ignamv** [comment]
By the way, I'm very curious about your circuit optimization project, if you're willing to share it. Even if the code is messy :)

**Comment by endolith** [comment]
@ignamv Well I was trying a very simple circuit first, and it wasn't working because I was trying to optimize with constraints, and scipy's basinhopping doesn't handle those sensibly, so I ended up [working on that instead](https://github.com/scipy/scipy/pull/7819). 

But anyway my very sloppy code is here: https://gist.github.com/endolith/6ecbaff2b44ce902b2025a4a45f1f336

**Comment by KrizLuk0** [comment]
I have the same problem, every simulation adds 13 MB to memory and nothing works... destroy, doesn't work, nothink
